# Generated by Django 4.2 on 2026-03-11 02:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='课程名称')),
                ('learn_count', models.IntegerField(default=0, verbose_name='学习人数')),
                ('difficulty', models.CharField(choices=[('primary', '初级'), ('middle', '中级')], default='primary', max_length=10, verbose_name='课程难度')),
                ('intro', models.TextField(verbose_name='课程介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'db_table': 'course_category',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='员工工号')),
                ('username', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('password', models.CharField(max_length=128, verbose_name='登录密码')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属部门')),
                ('status', models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='0', max_length=1, verbose_name='员工状态')),
                ('sync_time', models.DateTimeField(auto_now=True, verbose_name='最后同步时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='本地创建时间')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'employee',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(auto_now_add=True, verbose_name='同步时间')),
                ('sync_status', models.CharField(choices=[('success', '成功'), ('fail', '失败')], default='fail', max_length=10, verbose_name='同步状态')),
                ('fail_reason', models.TextField(blank=True, null=True, verbose_name='失败原因')),
                ('sync_count', models.IntegerField(default=0, verbose_name='同步员工数量')),
            ],
            options={
                'verbose_name': 'ERP员工同步日志',
                'verbose_name_plural': 'ERP员工同步日志',
                'db_table': 'erp_sync_log',
                'ordering': ['-sync_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('fill', '填空题')], max_length=10, verbose_name='考题类型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('score', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='题目分值')),
                ('generate_time', models.DateTimeField(auto_now_add=True, verbose_name='AI生成时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '考题信息',
                'verbose_name_plural': '考题信息',
                'db_table': 'exam_question',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='考试总分')),
                ('answer_time', models.DateTimeField(auto_now_add=True, verbose_name='作答时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='training.course', verbose_name='考试课程')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='training.employee', verbose_name='参考员工')),
            ],
            options={
                'verbose_name': '考试答卷',
                'verbose_name_plural': '考试答卷',
                'db_table': 'exam_paper',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资料名称')),
                ('file_type', models.CharField(choices=[('mp4', 'MP4视频'), ('ppt', 'PPT文档'), ('pptx', 'PPTX文档'), ('doc', 'Word文档'), ('docx', 'WordX文档'), ('pdf', 'PDF文档'), ('xlsx', 'Excel表格')], max_length=10, verbose_name='文件类型')),
                ('file_path', models.FileField(upload_to='course_resources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'ppt', 'pptx', 'doc', 'docx', 'pdf', 'xlsx'])], verbose_name='文件本地路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='training.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程资料',
                'verbose_name_plural': '课程资料',
                'db_table': 'course_resource',
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='章节名称')),
                ('chapter_type', models.CharField(choices=[('video', '视频'), ('doc', '文档')], max_length=10, verbose_name='章节类型')),
                ('sort', models.IntegerField(default=0, verbose_name='章节排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='training.course', verbose_name='所属课程')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='training.courseresource', verbose_name='关联资料')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'db_table': 'course_chapter',
                'unique_together': {('course', 'sort')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='training.coursecategory', verbose_name='所属分类'),
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='training.coursechapter', verbose_name='所属章节')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='training.employee', verbose_name='所属员工')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'db_table': 'learning_record',
                'unique_together': {('employee', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='ExamAnswerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_answer', models.TextField(verbose_name='员工答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='本题得分')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='training.exampaper', verbose_name='所属答卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.examquestion', verbose_name='关联考题')),
            ],
            options={
                'verbose_name': '考试答题明细',
                'verbose_name_plural': '考试答题明细',
                'db_table': 'exam_answer_detail',
                'unique_together': {('paper', 'question')},
            },
        ),
    ]
