# Generated by Django 4.2 on 2026-03-16 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('file', models.FileField(upload_to='training_docs/', verbose_name='上传文件')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '培训文档',
                'verbose_name_plural': '培训文档',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('fill', '填空题')], max_length=10, verbose_name='考题类型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('score', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='题目分值')),
                ('generate_time', models.DateTimeField(auto_now_add=True, verbose_name='AI生成时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.course', verbose_name='所属课程')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.courseresource', verbose_name='关联文档')),
            ],
            options={
                'verbose_name': '考题信息',
                'verbose_name_plural': '考题信息',
                'db_table': 'exam_question',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='考试总分')),
                ('answer_time', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='training.course', verbose_name='考试课程')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='training.employee', verbose_name='参考员工')),
            ],
            options={
                'verbose_name': '考试答卷',
                'verbose_name_plural': '考试答卷',
                'db_table': 'exam_paper',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(max_length=100, verbose_name='职称/岗位')),
                ('intro', models.TextField(verbose_name='简介')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='training.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程教师',
                'verbose_name_plural': '课程教师',
                'db_table': 'course_teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('content', models.TextField(verbose_name='问题详情')),
                ('is_solved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提问时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questions', to='training.course', verbose_name='所属课程')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_qa_questions', to='training.employee', verbose_name='提问人')),
            ],
            options={
                'verbose_name': '答疑问题',
                'verbose_name_plural': '答疑问题',
                'db_table': 'course_qa_question',
                'ordering': ['-is_solved', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_notice', models.BooleanField(default=False, verbose_name='是否为官方通知')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='training.course', verbose_name='所属课程')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_discussions', to='training.employee', verbose_name='发布人')),
            ],
            options={
                'verbose_name': '学习交流',
                'verbose_name_plural': '学习交流',
                'db_table': 'course_discussion',
                'ordering': ['-is_notice', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='是否为最佳答案')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_qa_answers', to='training.employee', verbose_name='回复人')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='training.coursequestion', verbose_name='关联问题')),
            ],
            options={
                'verbose_name': '问题回复',
                'verbose_name_plural': '问题回复',
                'db_table': 'course_qa_answer',
                'ordering': ['-is_accepted', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_answer', models.TextField(verbose_name='员工答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='本题得分')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='training.exampaper', verbose_name='所属答卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.examquestion', verbose_name='关联考题')),
            ],
            options={
                'verbose_name': '考试答题明细',
                'verbose_name_plural': '考试答题明细',
                'db_table': 'exam_answer_detail',
                'unique_together': {('paper', 'question')},
            },
        ),
        migrations.CreateModel(
            name='CourseComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='考试分数')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('complete_time', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_employees', to='training.course', verbose_name='完成课程')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_courses', to='training.employee', verbose_name='所属员工')),
            ],
            options={
                'verbose_name': '课程完成状态',
                'verbose_name_plural': '课程完成状态',
                'db_table': 'course_complete',
                'unique_together': {('employee', 'course')},
            },
        ),
    ]
