# Generated by Django 4.2 on 2026-03-11 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='file_path',
        ),
        migrations.AddField(
            model_name='courseresource',
            name='chapter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='training.coursechapter', verbose_name='所属章节'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'doc', 'docx', 'pdf', 'ppt', 'pptx'], message='仅支持MP4/AVI/MOV（视频）、DOC/DOCX/PDF（文档）、PPT/PPTX格式！')], verbose_name='资源文件'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('video', '视频'), ('doc', '文档'), ('ppt', 'PPT')], max_length=10, null=True, verbose_name='资源类型'),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='play_progress',
            field=models.IntegerField(default=0, verbose_name='视频播放进度(秒)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='从下拉框选一个刚才创建的分类', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='training.coursecategory', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('primary', '初级'), ('middle', '中级')], default='primary', help_text='选「初级」或「中级」', max_length=10, verbose_name='课程难度'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=models.TextField(help_text='简单写几句课程讲什么，比如「适合新手学习的物流基础概念」', verbose_name='课程介绍'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='学习人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='例如：国际物流基础入门、仓库管理实操', max_length=200, unique=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(help_text='例如：国际物流专业知识、客服部工作流程', max_length=100, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='sort',
            field=models.IntegerField(default=0, help_text='数字越小，分类在页面上越靠前（填 1、2、3... 即可）', verbose_name='排序值'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='chapter_type',
            field=models.CharField(choices=[('video', '视频'), ('doc', '文档')], help_text='视频资料选「视频」，文档资料选「文档」', max_length=10, verbose_name='章节类型'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(help_text='选这个章节属于哪门课', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='training.course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='name',
            field=models.CharField(help_text='和资料名称保持一致即可，比如「第一章 物流概述」', max_length=200, verbose_name='章节名称'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='resource',
            field=models.OneToOneField(help_text='选刚才上传的视频/文档资料', on_delete=django.db.models.deletion.CASCADE, related_name='chapter_resources', to='training.courseresource', verbose_name='关联资料'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='sort',
            field=models.IntegerField(default=0, help_text='数字越小，学习顺序越靠前（第一章填 1，第二章填 2...）', verbose_name='章节排序'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file_size',
            field=models.BigIntegerField(editable=False, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file_type',
            field=models.CharField(choices=[('doc', '文档'), ('video', '视频'), ('ppt', 'PPT')], default='doc', max_length=20, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=200, verbose_name='资源名称'),
        ),
    ]
