# Generated by Django 4.2 on 2026-03-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_courseresource_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.coursechapter', verbose_name='所属章节'),
        ),
    ]
